name: Create MSIX Bundle

on:
  push:
    tags:
      - '*' # Trigger on all tags
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/rust.yml

  msix_bundle:
    runs-on: windows-latest
    needs: build

    steps:

      - name: Checkout ðŸ“¥
        uses: actions/checkout@v6

      - name: Download x64 binaries ðŸ“¥
        uses: actions/download-artifact@v7
        with:
          name: windows-x64-binaries
          path: ./uwp/x64

      - name: Download ARM64 binaries ðŸ“¥
        uses: actions/download-artifact@v7
        with:
          name: windows-arm64-binaries
          path: ./uwp/arm64

      - name: Set up msixbundle-rs ðŸ§°
        run: |
          cargo install --git https://github.com/Choochmeque/msixbundle-rs msixbundle-cli

      - name: Create MSIX Bundle ðŸ§©
        run: |
          msixbundle-cli `
            --out-dir ./output `
            --dir-x64 ./uwp/x64/AppxContent `
            --dir-arm64 ./uwp/arm64/AppxContent

      - name: Upload MSIX Bundle ðŸ“¤
        uses: actions/upload-artifact@v6
        with:
          name: msix-bundle
          retention-days: 90
          path: ./output
